/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth/discord'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRoute
    }
  }
}

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
